# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Stuart Flanagan <stuartflanagan@gmail.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
