# Set the base image to Ubuntu
FROM node

# File Author / Maintainer
MAINTAINER Stuart Flanagan

# Provides cached layer for node_modules
# ADD package.json /tmp/package.json
# RUN cd /tmp && npm install
# RUN mkdir -p /src && cp -a /tmp/node_modules /src/

# Define working directory


# Expose port
EXPOSE  3000


CMD ["/bin/bash"]

CMD ["node", "/src"]
